<?php

/**
 * @file views_light_display.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_views_api().
 */
function views_light_display_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_light_display') . '/plugins',
  );
}

/**
 * Implements hook_views_plugins().
 */
function views_light_display_views_plugins() {
  $plugins = array(
    'display' => array(
      'light_display' => array(
        'title' => t('Light display'),
        'help' => t('Light view which can only be included from other modules'),
        'handler' => 'views_light_display_light_display',
        'theme' => 'views_view',
        'contextual links locations' => array(),
        'use ajax' => TRUE,
        'use pager' => TRUE,
        'use more' => TRUE,
        'accept attachments' => TRUE,
        'admin' => t('Light display'),
      ),
    ),
  );
  return $plugins;
}
